//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public int IdMaestro { get; set; }
        public Nullable<int> IdOrdenJedi { get; set; }
        public Nullable<int> IdSistemasAmenazados { get; set; }
        public Nullable<bool> Rango { get; set; }
    
        public virtual OrdenJedi OrdenJedi { get; set; }
        public virtual SistemasAmenazados SistemasAmenazados { get; set; }
    }
}
